homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/
# Enables configuration UI
config:
#Allow Python Scripts is python_scripts sub directory
python_script:
#Theme front page by user select
input_select:
  hass_theme:
    name: Themes
    options:
      - default
      - night
    initial: default
    icon: mdi:theme-light-dark

  alarm_zone:
    name: Alarm Zone
    options:
      - Mark Bedroom
      - Olivia Bedroom
      - Lounge
      - All
      - None
    initial: None
    icon: mdi:map-marker

input_boolean:
  alexa_alarm:
    name: Alexa Alarm
    initial: off
    icon: mdi:run

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret url
  ssl_certificate: !secret cert
  ssl_key: !secret key

#Link my IFTTT Maker
ifttt:
  key: !secret ifttt

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

#Networked Devices
device_tracker:
  platform: bt_home_hub_5
  host: 192.168.137.254

#Ikea Lights
tradfri:
   host: "192.168.137.35"
#   #api_key: "qEaisFnQT23cUC3R" #Not needed since version 57


media_player:
  #Bedroom OSMC
  - platform: kodi
    port: 1025
    username: !secret bedusr
    password: !secret bedpwd
    host: 192.168.137.12
    name: bedroom
  #Alexa Stick Kodi (TV)
  - platform: kodi
    port: 1025
    username: !secret tvusr
    password: !secret tvpwd
    host: 192.168.137.29
    name: TV
  #UTVPC Kodi
  - platform: kodi
    port: 1025
    username: !secret utvpcusr
    password: !secret utvpcpwd
    host: 192.168.137.1
    name: server
  #Alexa Stick All (TV)
  - platform: firetv
    name: Fire

#Caravan Monitor
panel_iframe:
  caravan:
    title: 'Caravan'
    icon: 'mdi:caravan'
    url: !secret caravan

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
#map:


switch:
  #Energenie Switches
  platform: command_line
  switches:
    coffee:
      friendly_name: Coffee Machine
      command_on: 'curl -X POST http://127.0.0.1/hub.php -d "action=status&id=1#on" -H "Content-Type:application/x-www-form-urlencoded" > /dev/null 2>&1'
      command_off: 'curl -X POST http://127.0.0.1/hub.php -d "action=status&id=1#off" -H "Content-Type:application/x-www-form-urlencoded" > /dev/null 2>&1'
      command_state: '/usr/bin/test -e /var/www/html/son1.lock && echo 0 || echo 1'
      value_template: '{{ value == "0" }}'
    echo:
      friendly_name: Amazon Echo
      command_on: 'curl -X POST http://127.0.0.1/hub.php -d "action=status&id=2#on" -H "Content-Type:application/x-www-form-urlencoded" > /dev/null 2>&1'
      command_off: 'curl -X POST http://127.0.0.1/hub.php -d "action=status&id=2#off" -H "Content-Type:application/x-www-form-urlencoded" > /dev/null 2>&1'
      command_state: '/usr/bin/test -e /var/www/html/son2.lock && echo 0 || echo 1'
      value_template: '{{ value == "0" }}'
    desk:
      friendly_name: Desk
      command_on: 'curl -X POST http://127.0.0.1/hub.php -d "action=status&id=3#on" -H "Content-Type:application/x-www-form-urlencoded" > /dev/null 2>&1'
      command_off: 'curl -X POST http://127.0.0.1/hub.php -d "action=status&id=3#off" -H "Content-Type:application/x-www-form-urlencoded" > /dev/null 2>&1'
      command_state: '/usr/bin/test -e /var/www/html/son3.lock && echo 0 || echo 1'
      value_template: '{{ value == "0" }}'
    bookcase:
      friendly_name: Bookcase
      command_on: 'curl -X POST http://127.0.0.1/hub.php -d "action=status&id=4#on" -H "Content-Type:application/x-www-form-urlencoded" > /dev/null 2>&1'
      command_off: 'curl -X POST http://127.0.0.1/hub.php -d "action=status&id=4#off" -H "Content-Type:application/x-www-form-urlencoded" > /dev/null 2>&1'
      command_state: '/usr/bin/test -e /var/www/html/son4.lock && echo 0 || echo 1'
      value_template: '{{ value == "0" }}'

# Track the sun
sun:

#Alexa Readback
alexa:
  flash_briefings:
    hastatus:
      title: Home Assistant Status
      text: >
        Currently the flat is at {{ states("sensor.inside_temp") }} degrees and there are {{ states("sensor.plex_server") }} plex viewers.
        {% for attr in states.sensor.plex_server.attributes %}
         {%- if not attr=="friendly_name" and not attr=="unit_of_measurement" and not attr=="icon" -%}
          {{attr}} is watching: {{states.sensor.plex_server.attributes[attr]}}
         {%- endif %}
        {%- endfor -%}
    tempread:
      title: Flat Temperaute
      text: Currently the flat is at {{ states("sensor.inside_temp") }} degrees
    plexread:
     title: Plex users equals {{ states("sensor.plex_server") }}
     text: >
        {% for attr in states.sensor.plex_server.attributes %}
         {%- if not attr=="friendly_name" and not attr=="unit_of_measurement" and not attr=="icon" -%}
          {{attr}} is watching: {{states.sensor.plex_server.attributes[attr]}}
         {%- endif %}
        {%- endfor -%}


sensor:
    # Weather prediction
  - platform: yweather
    woeid: !secret weather
    name: Outside
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
      - weather_current
      - temperature
    scan_interval: 600
    #Flat Forecast
  - platform: yweather
    woeid: !secret weather
    forecast: 1
    name: flat_day1
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
    scan_interval: 10800
  - platform: yweather
    woeid: !secret weather
    forecast: 2
    name: flat_day2
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
    scan_interval: 10800
  - platform: yweather
    woeid: !secret weather
    forecast: 3
    name: flat_day3
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
    scan_interval: 10800
  - platform: yweather
    woeid: !secret weather
    forecast: 4
    name: flat_day4
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
    scan_interval: 10800

    # Weather prediction
  - platform: yweather
    woeid: !secret caravan_w
    name: Caravan Outside
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
      - weather_current
      - temperature
    scan_interval: 600
    #Caravan Forecast
  - platform: yweather
    woeid: !secret caravan_w
    forecast: 1
    name: caravan_day1
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
    scan_interval: 10800
  - platform: yweather
    woeid: !secret caravan_w
    forecast: 2
    name: caravan_day2
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
    scan_interval: 10800
  - platform: yweather
    woeid: !secret caravan_w
    forecast: 3
    name: caravan_day3
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
    scan_interval: 10800
  - platform: yweather
    woeid: !secret caravan_w
    forecast: 4
    name: caravan_day4
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
    scan_interval: 10800
##Template to display forecast in single Card
  - platform: template
    sensors:
      weekday:
        friendly_name: 'Weekday'
        value_template: '{{ now().strftime("%A") }}'
      fforecast_today:
        friendly_name: "Today"
        value_template: >
          {{states.sensor.outside_condition.state}} - Min {{states.sensor.outside_temperature_min.state|round(0)}}°C / Max {{states.sensor.outside_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.outside_condition.attributes.entity_picture}}
      fforecast_1:
        value_template: >
          {{states.sensor.flat_day1_condition.state}} - Min {{states.sensor.flat_day1_temperature_min.state|round(0)}}°C / Max {{states.sensor.flat_day1_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.flat_day1_condition.attributes.entity_picture}}
      fforecast_2:
        value_template: >
          {{states.sensor.flat_day2_condition.state}} - Min {{states.sensor.flat_day2_temperature_min.state|round(0)}}°C / Max {{states.sensor.flat_day2_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.flat_day2_condition.attributes.entity_picture}}
      fforecast_3:
        value_template: >
          {{states.sensor.flat_day3_condition.state}} - Min {{states.sensor.flat_day3_temperature_min.state|round(0)}}°C / Max {{states.sensor.flat_day3_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.flat_day3_condition.attributes.entity_picture}}
      fforecast_4:
        value_template: >
          {{states.sensor.flat_day4_condition.state}} - Min {{states.sensor.flat_day4_temperature_min.state|round(0)}}°C / Max {{states.sensor.flat_day4_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.flat_day4_condition.attributes.entity_picture}}

      cforecast_today:
        friendly_name: "Today"
        value_template: >
          {{states.sensor.caravan_outside_condition.state}} - Min {{states.sensor.caravan_outside_temperature_min.state|round(0)}}°C / Max {{states.sensor.caravan_outside_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.caravan_outside_condition.attributes.entity_picture}}
      cforecast_1:
        value_template: >
          {{states.sensor.caravan_day1_condition.state}} - Min {{states.sensor.caravan_day1_temperature_min.state|round(0)}}°C / Max {{states.sensor.caravan_day1_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.caravan_day1_condition.attributes.entity_picture}}
      cforecast_2:
        value_template: >
          {{states.sensor.caravan_day2_condition.state}} - Min {{states.sensor.caravan_day2_temperature_min.state|round(0)}}°C / Max {{states.sensor.caravan_day2_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.caravan_day2_condition.attributes.entity_picture}}
      cforecast_3:
        value_template: >
          {{states.sensor.caravan_day3_condition.state}} - Min {{states.sensor.caravan_day3_temperature_min.state|round(0)}}°C / Max {{states.sensor.caravan_day3_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.caravan_day3_condition.attributes.entity_picture}}
      cforecast_4:
        value_template: >
          {{states.sensor.caravan_day4_condition.state}} - Min {{states.sensor.caravan_day4_temperature_min.state|round(0)}}°C / Max {{states.sensor.caravan_day4_temperature_max.state|round(0)}}°C
        entity_picture_template: >
          {{states.sensor.caravan_day4_condition.attributes.entity_picture}}

    #Inside Temp
  - platform: command_line
    name: Inside Temp
    command: /usr/bin/php -r 'echo round(shell_exec("/usr/local/bin/temper-poll -c"))+3;'
    unit_of_measurement: "°C"
    scan_interval: 600
    #Carvan Temp
  - platform: command_line
    name: Caravan Temp
    command: "/bin/bash /home/homeassistant/.homeassistant/caravan_sensor.sh"
    unit_of_measurement: "°C"
    scan_interval: 600

    #Plex Server
  - platform: plex
    host: 192.168.137.1
    port: 32400
    name: Plex Server
    username: !secret plexusr
    password: !secret plexpwd

#camera image
camera:
  - platform: local_file
    name: Current Image
    file_path: /var/www/html/images/camera.jpg

#Fake buttons for Alexa config
emulated_hue:
  host_ip: 192.168.137.12
  off_maps_to_on_domains:
    - script
  expose_by_default: false
  exposed_domains:
    - switch
    - script
    - scene

#Restart Bedroom restart_osmc
shell_command:
  restartosmc: echo homeassistant | sudo -S systemctl restart mediacenter
  reboot: echo homeassistant | sudo -S reboot
# Text to speech
tts:
  - platform: google

#Notifications from PushBullet
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret push




group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
